name: linter - check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-python
        uses: actions/setup-python@v2
      - name: install1
        run:  pip install poetry
      - name: install flake8
        run: pip install poetry pip install flake8
      - name: my-step
        run: make lint
