name: linter - check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install1
        run:  pip install poetry
      - name: my-step
        run: make lint
